"""esquema inicial DATA_MODEL

Revision ID: 07105cfdb907
Revises: 
Create Date: 2026-06-03 23:23:17.433482
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07105cfdb907'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cajeros',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('usuario', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.Enum('cajero', 'administrador', name='rol_cajero'), server_default=sa.text("'cajero'"), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('productos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('codigo_barras', sa.Text(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_tasa', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.160'), nullable=False),
    sa.Column('existencia', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('controla_stock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('precio >= 0', name='ck_productos_precio_no_negativo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_productos_codigo', 'productos', ['codigo_barras'], unique=False)
    op.create_index('idx_productos_nombre', 'productos', ['nombre'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.Enum('venta', 'devolucion', 'ajuste', 'import', 'alta', name='tipo_movimiento'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('cajero_id', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cajero_id'], ['cajeros.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movstock_producto', 'movimientos_stock', ['producto_id'], unique=False)
    op.create_table('turnos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('cajero_id', sa.BigInteger(), nullable=False),
    sa.Column('abierto_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fondo_inicial', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('efectivo_contado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cajero_id'], ['cajeros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turnos_cajero', 'turnos', ['cajero_id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('folio', sa.Text(), nullable=False),
    sa.Column('turno_id', sa.BigInteger(), nullable=False),
    sa.Column('cajero_id', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.Enum('abierta', 'pagada', 'cancelada', 'devuelta_parcial', 'devuelta_total', name='estado_venta'), server_default=sa.text("'abierta'"), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('iva_total', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('requiere_factura', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('exportada_fiscal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cajero_id'], ['cajeros.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_index('idx_ventas_fecha', 'ventas', ['creado_en'], unique=False)
    op.create_index('idx_ventas_turno', 'ventas', ['turno_id'], unique=False)
    op.create_table('devoluciones',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('venta_id', sa.BigInteger(), nullable=False),
    sa.Column('turno_id', sa.BigInteger(), nullable=False),
    sa.Column('cajero_id', sa.BigInteger(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cajero_id'], ['cajeros.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('venta_id', sa.BigInteger(), nullable=False),
    sa.Column('medio', sa.Enum('efectivo', 'tarjeta_point', name='medio_pago'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recibido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cambio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', 'cancelado', name='estado_pago'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('mp_order_id', sa.Text(), nullable=True),
    sa.Column('mp_idempotency', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monto > 0', name='ck_pagos_monto_positivo'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pagos_mp_order', 'pagos', ['mp_order_id'], unique=True, postgresql_where=sa.text('mp_order_id IS NOT NULL'))
    op.create_index('idx_pagos_venta', 'pagos', ['venta_id'], unique=False)
    op.create_table('venta_lineas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('venta_id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_tasa', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_venta_lineas_cantidad_positiva'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lineas_venta', 'venta_lineas', ['venta_id'], unique=False)
    op.create_table('devolucion_lineas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('devolucion_id', sa.BigInteger(), nullable=False),
    sa.Column('venta_linea_id', sa.BigInteger(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_devolucion_lineas_cantidad_positiva'),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devoluciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venta_linea_id'], ['venta_lineas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devolucion_lineas')
    op.drop_index('idx_lineas_venta', table_name='venta_lineas')
    op.drop_table('venta_lineas')
    op.drop_index('idx_pagos_venta', table_name='pagos')
    op.drop_index('idx_pagos_mp_order', table_name='pagos', postgresql_where=sa.text('mp_order_id IS NOT NULL'))
    op.drop_table('pagos')
    op.drop_table('devoluciones')
    op.drop_index('idx_ventas_turno', table_name='ventas')
    op.drop_index('idx_ventas_fecha', table_name='ventas')
    op.drop_table('ventas')
    op.drop_index('idx_turnos_cajero', table_name='turnos')
    op.drop_table('turnos')
    op.drop_index('idx_movstock_producto', table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index('idx_productos_nombre', table_name='productos')
    op.drop_index('idx_productos_codigo', table_name='productos')
    op.drop_table('productos')
    op.drop_table('cajeros')
    # ### end Alembic commands ###
    # Los tipos ENUM se crean implícitamente al crear las tablas; hay que
    # eliminarlos a mano para que un re-upgrade tras downgrade no falle.
    bind = op.get_bind()
    for enum_name in (
        'estado_venta',
        'medio_pago',
        'estado_pago',
        'tipo_movimiento',
        'rol_cajero',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
