"""ventas.descuento_global

Revision ID: 9e479b911218
Revises: 07105cfdb907
Create Date: 2026-06-03 23:46:13.961627
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e479b911218'
down_revision: Union[str, None] = '07105cfdb907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('descuento_global', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'descuento_global')
    # ### end Alembic commands ###
